<?php 
/**
	Admin Page Framework v3.8.15 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/kvcore>
	Copyright (c) 2013-2017, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class kvCORE_AdminPageFramework_Form_View___CSS_term_meta extends kvCORE_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".kvcore-form-table-outer-row-term_meta,.kvcore-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.kvcore-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.kvcore-form-table-term_meta .kvcore-sectionset,.kvcore-form-table-term_meta .kvcore-section {margin-bottom: 0;}.kvcore-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.kvcore-form-table-term_meta.add-new-term .kvcore-section .form-table > tbody > tr > td,.kvcore-form-table-term_meta.add-new-term .kvcore-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.kvcore-form-table-term_meta.add-new-term .kvcore-field {width: auto;}.kvcore-form-table-term_meta.add-new-term .kvcore-field {max-width: 100%;}.kvcore-form-table-term_meta.add-new-term .sortable .kvcore-field {width: auto;} .kvcore-form-table-term_meta.add-new-term .kvcore-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.kvcore-form-table-term_meta .kvcore-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.kvcore-form-table-term_meta .kvcore-collapsible-title h3 {margin: 0;}.kvcore-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.kvcore-form-table-term_meta .kvcore-section-tab h4 {margin: 0;} ";
    }
}
